name: teammetrics
description: A web server application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^2.5.0+1
  github:
#    path: ../github.dart/
    git:
      url: git@github.com:dustinlessard-wf/github.dart.git
      ref: enhancedList
  w_transport: ^3.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
